tap "heroku/brew"
tap "homebrew/cask"
tap "homebrew/services"
tap "jesseduffield/lazygit"

# This block should be synced to Brewfile.codespaces
brew "gh"
brew "jq"
brew "gpg"
brew "yarn"
brew "ripgrep"
brew "git-lfs"
brew "bat"
brew "tldr"
brew "exa"
brew "direnv"
brew "the_silver_searcher"

brew "asciinema"
brew "tmuxinator"
brew "starship"
brew "rbspy"
brew "gotags"
brew "nvim"
brew "node"
brew "ruby"
brew "rbenv"
brew "tmux"
brew "lazygit"
brew "heroku"

if OS.mac?
  brew "pinentry-mac"
  brew "mas"
  brew "cocoapods"
  brew "trash"
  brew "reattach-to-user-namespace"

  cask "iterm2"
  cask "visual-studio-code"
  cask "1password"
  cask "1password-cli"
  cask "microsoft-edge"
  cask "docker"
  cask "zoomus"
  cask "keybase"
  cask "gpg-suite-pinentry"
  cask "divvy"
  cask "parsec"
  cask "powershell"
  cask "github"
  cask "ngrok"
  cask "postman"
  cask "wireshark"
  cask "notion"
  cask "firefox"
  cask "secretive"
  cask "multitouch"

  mas "Slack", id: 803453959
  mas "iMovie", id: 408981434
  mas "OneDrive", id: 823766827
  mas "Moom", id: 419330170
end