---
- name: Alacritty config
  hosts: localhost
  connection: local
  vars:
    is_mac: "{{ ansible_facts['os_family'] == 'Darwin' }}"
  tasks:
    - name: Install Alacritty config
      file:
        src: '~/.dotfiles/modules/alacritty/alacritty.yml'
        dest: '~/.alacritty.yml'
        state: link
        force: yes