[username]
show_always = true

[hostname]
ssh_only = false

[directory]
truncate_to_repo = false
truncation_length = 0

[dotnet]
symbol = "\ue77f "

[golang]
format = "[$symbol $version]($style) "

[ruby]
format = "[$symbol $version]($style) "
