---
- name: Tmux
  hosts: localhost
  connection: local
  vars:
    is_mac: "{{ ansible_facts['os_family'] == 'Darwin' }}"
  tasks:
    - name: Install Tmux
      become: yes
      apt:
        package: tmux
      when: not is_mac

    - name: Install Tmux config
      file:
        src: '~/.dotfiles/modules/tmux/{{ item }}'
        dest: '~/.{{ item }}'
        state: link
      loop:
        - "tmux.conf"
        - "tmux.conf.local"