---
- name: Core shell
  hosts: localhost
  connection: local
  vars:
    is_mac: "{{ ansible_facts['os_family'] == 'Darwin' }}"
  tasks:
    - name: Linking zshrc
      file:
        src: "~/.dotfiles/modules/zsh/zshrc.sh"
        dest: "~/.zshrc"
        state: link
        force: yes

    - name: Linking zprofile
      file:
        src: "~/.dotfiles/modules/zsh/zprofile.sh"
        dest: "~/.zprofile"
        state: link
        force: yes
    
    - name: Create ZSH local storage directory
      file:
        dest: "~/.dotfiles/local/zsh"
        state: directory

    - name: Install Antigen
      get_url:
        url: https://git.io/antigen
        dest: ~/.dotfiles/local/zsh/antigen.zsh
        checksum: sha256:3fc9472388232ecb7cf2c6d28f06109d857afa1c1897ce1bbeed40aced6e6518