---
- name: Core playbook containing the main tools used on any machine
  hosts: localhost
  connection: local
  vars:
    is_mac: "{{ ansible_facts['os_family'] == 'Darwin' }}"
  tasks:
    - name: Create BIN dir
      file:
        state: directory
        dest: ~/bin
    - name: Create CODE dir
      file:
        state: directory
        dest: ~/code
- name: Install packages
  import_playbook: packages.yml