---
- name: Core packages
  hosts: localhost
  connection: local
  vars:
    is_mac: "{{ ansible_facts['os_family'] == 'Darwin' }}"
  tasks:
    - name: Enable HTTPS APT support
      become: yes
      apt:
        package:
          - apt-transport-https
          - ca-certificates
          - software-properties-common
      when: not is_mac

    # Linux core packages
    - name: Update apt package list
      become: yes
      apt:
        update_cache: yes
      register: apt_update
      retries: 5
      until: apt_update is success
      when: not is_mac

    - name: Install core packages
      become: yes
      apt:
        package:
          - curl
          - jq
          - unzip
          - uuid
          - zsh
          - fzf
          - git
          - shellcheck
      when: not is_mac

    - name: Upgrade to latest APT packages
      become: yes
      apt:
        upgrade: yes
      when: not is_mac
    
    # MacOS Core Packages
    - name: Update homebrew
      homebrew:
        update_homebrew: yes
      when: is_mac

    - name: Install core homebrew packages
      homebrew:
        name:
          - jq
          - ripgrep
          - bat
          - tldr
          - exa
          - direnv
          - the_silver_searcher
          - tmux
          - mas
          - reattach-to-user-namespace
      when: is_mac
