" Update MYVIMRC
let $MYVIMRC="~/.dotfiles/vim.symlink/vimrc"

set ff=unix

" Make windows accept unixy stuff
if has('win32') || has('win64')
    set runtimepath=~/.vim,$VIM/vimfiles,$VIM,$VIM/vimfiles/after,~/.vim/after
    set dir=$TEMP
endif

let g:pathogen_disabled = []
if !has('python')
    call add(g:pathogen_disabled, 'omnisharp-vim')
endif

"Load pathogen
source ~/.vim/bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()

"Psh, compatibility schmompatibility
set nocompatible

filetype plugin indent on    " required

"Set Color Scheme and font

set guifont=Sauce_Code_Powerline:h12
if has('gui_running')
	colorscheme solarized

	" Maximize the window on launch
	if has('win32') || has('win64')
		au GUIEnter * simalt ~x
	endif
	if has("unix")
	  let s:uname = system("uname")
	  if s:uname == "Darwin\n"
	    " Do Mac stuff here
	    set fuopt=maxhorz,maxvert
	    "au GUIEnter * set fullscreen
	  endif
	endif
endif

let g:airline_powerline_fonts=1

set background=dark

"Configure some simple settings
set backspace=2 "Backspace over indents, eol, etc.

"Set up VIM GUIs
set guioptions-=m " Hide menu bar
set guioptions-=T " Remove toolbar
set guioptions-=r
set guioptions-=L " Remove scrollbars

"Syntax Highlighting ON!
syntax on

"Indentation configuration
set tabstop=4
set shiftwidth=4
set softtabstop=4
set smarttab
set expandtab

" Statusline and line numbers
set laststatus=2
set number

" Macros/Mappings
nmap <S-Enter> O<Esc>
nmap <CR> o<Esc>

" Remove the ability to "derp around using the arrow keys"
"map <up> <nop>
"map <down> <nop>
"map <left> <nop>
"map <right> <nop>
"imap <up> <nop>
"imap <down> <nop>
"imap <left> <nop>
"imap <right> <nop>

" Use Ctrl-J and Ctrl-K to switch windows
map <C-J> <C-W>j<C-W>_
map <C-K> <C-W>k<C-W>_

" Configure NERDTree and NERDTree tabs
map <C-N> <Esc>:NERDTreeToggle<CR>
map <C-O> <Esc>:NERDTreeFocusToggle<CR>
let g:nerdtree_tabs_open_on_gui_startup=0
let g:nerdtree_tabs_open_on_new_tab=0

" CtrlP settings
let g:ctrlp_working_path_mode='ra'
