#!/usr/bin/env bash

set -eo pipefail
[ "$DEBUG" = "1" ] && set -x
DOTFILES_ROOT="$( cd "$(dirname $(dirname "$0"))" ; pwd -P )"
cd $DOTFILES_ROOT

# If ansible is here already, just exit successfully
if ! type ansible >/dev/null 2>&1; then
    banner "installing ansible"

    uname=$(uname)
    if [ "$uname" == "Linux" ]; then
        if type apt >/dev/null 2>&1; then
            heading "updating apt..."
            sudo apt-get update -qyy
            heading "installing ansible..."
            sudo apt-get install -qyy ansible
        else
            echo "TODO: unknown linux distribution" 1>&2
            exit 1
        fi
    elif [ "$uname" == "Darwin" ]; then
        echo "TODO: macOS" 1>&2
        exit 1
    fi
fi

# Playbooks that will be run automatically during setup
PLAYBOOKS=(base ssh vim tmux git)

# Apply the base playbooks
bin/apply "${PLAYBOOKS[@]}"