---
- name: Vim
  hosts: localhost
  connection: local
  vars:
    is_mac: "{{ ansible_facts['os_family'] == 'Darwin' }}"
  tasks:
    - name: Install Vim
      become: yes
      apt:
        package: vim
      when: not is_mac

    - name: Install Vim directory
      file:
        src: "~/.dotfiles/modules/vim"
        dest: "~/.vim"
        state: link
        force: yes

    - name: Install Vim config
      file:
        src: "~/.dotfiles/modules/vim/vimrc.vim"
        dest: "~/.vimrc"
        state: link
        force: yes