- name: NodeJS
  hosts: localhost
  connection: local

  tasks:
    - name: Install Node Version Manager
      shell:
        cmd: "curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.35.2/install.sh | bash"
        warn: false
      args:
        creates: ~/.nvm/install.sh
