---
- name: Core playbook containing the main tools used on any dev workstation
  hosts: localhost
  connection: local
  vars:
    is_mac: "{{ ansible_facts['os_family'] == 'Darwin' }}"
  tasks:
- name: Install packages
  import_playbook: packages.yml
