---
- name: Core packages
  hosts: localhost
  connection: local
  vars:
    is_mac: "{{ ansible_facts['os_family'] == 'Darwin' }}"
    is_debian: "{{ (ansible_facts['distribution'] == 'Debian') or (ansible_facts['distribution'] == 'Ubuntu') }}"
    is_codespaces: "{{ 'CODESPACES' in ansible_facts['env'] }}"
  tasks:
    - name: Install packages (Debian)
      when: is_debian
      block:
        # Linux core packages
        - name: Update apt package list
          become: yes
          apt:
            update_cache: yes
          register: apt_update
          retries: 5
          until: apt_update is success

        - name: Install core packages
          become: yes
          apt:
            package:

    - name: Install packages (macOS)
      when: is_mac
      block:
        # MacOS Core Packages
        - name: Update homebrew
          homebrew:
            update_homebrew: yes

        - name: Install homebrew packages
          homebrew:
            name:
              - mas

        - name: Install homebrew casks
          homebrew_cask:
            name:
              - visual-studio-code
              - 1password
              - 1password-cli
              - microsoft-edge
              - slack
              - alacritty
              - zoom
              - spotify
              - hammerspoon

        - name: Install App Store Apps
          mas:
            id:
              - 1480068668 # Facebook Messenger
