query($queryText: String!, $cursor: String) {
	search(type: ISSUE, query: $queryText, first: 100, after: $cursor) {
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
    	... on PullRequest {
        number
        title
        repository { nameWithOwner }
        headRef { name }
      } 
    }
  }
}