#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

cd "$DIR"

if [ ! -d "./pure" ]; then
	git clone "https://github.com/sindresorhus/pure.git"
else
	cd "./pure"
	git pull --rebase --autostash
fi
