---
- name: Git
  hosts: localhost
  connection: local
  vars:
    is_mac: "{{ ansible_facts['os_family'] == 'Darwin' }}"
    is_codespaces: "{{ 'CODESPACES' in ansible_facts['env'] }}"
  tasks:
    - name: Install Git
      become: yes
      apt:
        package: git
      when:
        - not is_mac
        - not is_codespaces

    - name: Install Root Git config
      file:
        src: '~/.dotfiles/modules/git/gitconfig'
        dest: '~/.gitconfig'
        state: link
        force: yes
